#!/usr/bin/env python3
"""Generate a synthetic photo-and-video library for exercising the pipeline.

WHAT THIS LIBRARY IS NOT
========================
Nothing in it is a photograph. Every still is drawn procedurally with PIL from
a seeded RNG, and every clip is encoded by FFmpeg from one of those drawings.

The "faces" are cartoons: a skin-coloured oval, two eye ellipses with pupils,
brows, a nose line and a mouth arc. They exist so the face stack has something
with roughly face-shaped structure to run against, and so a *plumbing* failure
-- a detector that is never actually called, a BGR/RGB swap, a resize
convention mismatch, a post-processing step that returns an empty tensor --
shows up as a crash or an obviously wrong count instead of as silence.

THEY PROVE NOTHING ABOUT DETECTION QUALITY. A detector that finds all of them
may find no real faces, and a detector that finds none of them may be excellent
on real ones. Any recall/precision number measured on this library is
meaningless and must never reach a model card, an eval report, or a regression
gate. Real numbers come from `packages/eval-harness/` run against a consented
benchmark library of real photographs.

The same caveat applies, less obviously, to everything else here. Synthetic
stills have clean exposure, no motion blur, no chroma noise from a real sensor,
no lens character and no JPEG generation loss. Quality scores, aesthetic
scores and dedupe thresholds tuned against this library will not transfer.

WHAT IT IS FOR
==============
The user's own photographs are not a test fixture. Exercising the pipeline
must never require pointing it at a real photo folder, and `~/Downloads` is
explicitly off limits. This produces a library that is *hostile in the ways
that matter* so the pipeline can be run end to end on a machine that has never
seen a real image:

  * near-duplicate bursts (the same scene five times, barely varied) -- the
    thing dedupe exists for, and the thing a too-generous Hamming threshold
    silently over-merges
  * a still with no EXIF date at all, and a filename that matches no date
    pattern, so it must come out `precision: unknown` rather than at the epoch
  * stills whose EXIF date and filesystem mtime disagree by years -- the
    "copied off an old hard drive" case, where trusting mtime reorders a
    library
  * a GoPro chaptered recording spanning files (GX010012 / GX020012 / ...),
    matching `workers/ingest/src/gopro.rs` exactly, plus a legacy
    GOPR0044 / GP010044 pair, which uses a *different* index convention
  * a vertical clip and horizontal clips, at 24, 25, 29.97, 30 and 60 fps
  * a truncated JPEG, a truncated MP4 and a zero-byte file, which must fail
    loudly and be quarantined -- never silently skipped
  * an EXIF-orientation-6 still, whose oriented size is the transpose of its
    stored size
  * unsupported strays (a .txt, an .xmp sidecar) of the kind every real
    library contains

Everything is deterministic from `--seed`: same seed, same bytes, same BLAKE3,
same media_ids. The manifest records the BLAKE3 of every file, which is exactly
the `media_id` the ingest worker will derive, so a consumer can assert against
identities rather than guessing from filenames.

Usage:
    python3 scripts/demo/make_library.py --out /tmp/demo-library
    python3 scripts/demo/make_library.py --out DIR --seed 7 --stills 200 --clips 10
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import random
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Sequence

try:
    import numpy as np
    from PIL import Image, ImageDraw, ImageFilter
except ImportError as error:  # pragma: no cover - dependency guard
    raise SystemExit(
        f"make_library needs Pillow and numpy ({error}).\n"
        "  pip install pillow numpy"
    )

# Bump when the generated bytes change for a fixed seed. A consumer that pins
# expectations can compare this instead of re-deriving them.
# 2: OffsetTimeOriginal / OffsetTimeDigitized are written for the three events
#    whose cameras would have written them, so those files resolve to a real
#    instant and an album can be planned. Every media_id changes at this bump.
GENERATOR_VERSION = 2
MANIFEST_NAME = "MANIFEST.json"

# EXIF tag numbers. Written through Pillow's Exif object rather than a helper
# library so this has no dependency beyond Pillow; DateTimeOriginal and
# DateTimeDigitized must land in the Exif sub-IFD (0x8769), not IFD0, or
# kamadak-exif on the Rust side will report them as unknown TIFF tags.
TAG_MAKE = 0x010F
TAG_MODEL = 0x0110
TAG_ORIENTATION = 0x0112
TAG_SOFTWARE = 0x0131
TAG_DATETIME = 0x0132
TAG_EXIF_IFD = 0x8769
TAG_DATETIME_ORIGINAL = 0x9003
TAG_DATETIME_DIGITIZED = 0x9004
# OffsetTimeOriginal / OffsetTimeDigitized (EXIF 2.31). Without one of these a
# DateTimeOriginal is a wall-clock reading with no zone, which is not an
# instant -- `captured_at.utc` stays null, media-db's chronological listing
# cannot order the library, and the album stage refuses to build a book from
# undated media. Deliberately NOT written by every camera here: see Event.
TAG_OFFSET_TIME_ORIGINAL = 0x9011
TAG_OFFSET_TIME_DIGITIZED = 0x9012
TAG_LENS_MODEL = 0xA434


# ---------------------------------------------------------------------------
# Where we refuse to write
# ---------------------------------------------------------------------------

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _paths import real_media_location  # noqa: E402


def check_destination(out: Path, force: bool) -> None:
    """Refuse destinations that could contain, or be mistaken for, real media.

    Writing a synthetic library *into* a real photo folder is the exact
    accident this script exists to prevent, and `--force` would then delete
    real files.
    """
    resolved = out.expanduser().resolve()

    reason = real_media_location(resolved)
    if reason is not None:
        raise SystemExit(
            f"refusing to write into {resolved}: {reason}.\n"
            "  pick a scratch directory, e.g. --out /tmp/demo-library"
        )

    if not resolved.exists():
        return
    if not resolved.is_dir():
        raise SystemExit(f"--out exists and is not a directory: {resolved}")

    entries = [p for p in resolved.iterdir() if p.name != ".DS_Store"]
    if not entries:
        return
    if not (resolved / MANIFEST_NAME).is_file():
        raise SystemExit(
            f"{resolved} is not empty and has no {MANIFEST_NAME}, so it was not "
            "generated by this script.\n"
            "  refusing to touch it -- pick an empty directory."
        )
    if not force:
        raise SystemExit(
            f"{resolved} already holds a generated library. Pass --force to replace it."
        )


# ---------------------------------------------------------------------------
# Deterministic randomness
# ---------------------------------------------------------------------------


def stream(seed: int, *labels: object) -> random.Random:
    """An independent RNG stream, named rather than positional.

    One shared Random() would make every value depend on the order everything
    else was generated in, so adding a photo to event A would change every
    pixel of event D and every media_id in the library. Naming the stream keeps
    a file's bytes a function of that file's identity alone.
    """
    key = "\x1f".join([str(seed), *(str(label) for label in labels)])
    digest = hashlib.blake2b(key.encode("utf-8"), digest_size=8).digest()
    return random.Random(int.from_bytes(digest, "big"))


# ---------------------------------------------------------------------------
# Scene drawing
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Palette:
    sky_top: tuple[int, int, int]
    sky_bottom: tuple[int, int, int]
    hill_far: tuple[int, int, int]
    hill_near: tuple[int, int, int]
    ground: tuple[int, int, int]
    sun: tuple[int, int, int]


PALETTES = {
    "beach_noon": Palette((92, 156, 214), (188, 214, 232), (108, 132, 128), (196, 178, 138), (214, 198, 156), (255, 244, 214)),
    "beach_sunset": Palette((44, 52, 104), (232, 142, 92), (86, 66, 84), (58, 44, 52), (96, 74, 68), (255, 206, 122)),
    "festival_night": Palette((14, 12, 34), (58, 30, 62), (36, 26, 54), (26, 18, 36), (32, 24, 40), (255, 196, 96)),
    "hill_morning": Palette((122, 172, 206), (206, 220, 226), (96, 122, 106), (62, 90, 72), (86, 108, 74), (250, 248, 230)),
    "indoor_warm": Palette((92, 74, 60), (146, 118, 92), (110, 86, 66), (78, 60, 46), (120, 96, 74), (255, 224, 168)),
}

SKIN_TONES = [
    (232, 194, 164), (214, 168, 132), (176, 128, 96),
    (140, 96, 68), (100, 68, 48), (246, 214, 190),
]
HAIR_TONES = [(38, 30, 26), (62, 44, 32), (24, 20, 20), (96, 72, 48), (140, 128, 120)]
SHIRT_TONES = [
    (196, 74, 68), (66, 108, 168), (238, 196, 84), (74, 142, 108),
    (222, 226, 232), (128, 84, 156), (240, 138, 92),
]


@dataclass(frozen=True)
class Scene:
    """Everything that decides what one drawing looks like.

    A near-duplicate burst is five Scenes that differ only in `jitter`.
    """

    palette: str
    horizon: float            # 0..1, fraction of height
    sun_x: float              # 0..1
    sun_r: float              # fraction of width
    ridge_seed: int
    subjects: tuple[tuple[float, float, float, int, int, int], ...]
    # (x, y_base, scale, skin_idx, hair_idx, shirt_idx)
    grain: int
    jitter: tuple[float, float, float] = (0.0, 0.0, 0.0)  # dx, dy, brightness


def build_scene(rng: random.Random, palette: str, subject_count: int) -> Scene:
    horizon = rng.uniform(0.34, 0.66)
    subjects = []
    for index in range(subject_count):
        subjects.append((
            rng.uniform(0.12, 0.88),
            rng.uniform(horizon + 0.05, 0.95),
            rng.uniform(0.10, 0.26),
            rng.randrange(len(SKIN_TONES)),
            rng.randrange(len(HAIR_TONES)),
            rng.randrange(len(SHIRT_TONES)),
        ))
    return Scene(
        palette=palette,
        horizon=horizon,
        sun_x=rng.uniform(0.08, 0.92),
        sun_r=rng.uniform(0.03, 0.11),
        ridge_seed=rng.randrange(1 << 30),
        subjects=tuple(subjects),
        grain=rng.randrange(1 << 30),
    )


def jittered(scene: Scene, index: int, rng: random.Random) -> Scene:
    """One frame of a burst: the same scene, moved a hair.

    The magnitudes are small on purpose. A burst that varies a lot is not a
    burst, and would test nothing -- dedupe is supposed to catch the case where
    the photographer held the shutter down and the subject blinked.
    """
    return Scene(
        palette=scene.palette,
        horizon=scene.horizon,
        sun_x=scene.sun_x,
        sun_r=scene.sun_r,
        ridge_seed=scene.ridge_seed,
        subjects=scene.subjects,
        grain=scene.grain + index,  # different sensor noise, same picture
        jitter=(
            rng.uniform(-0.006, 0.006),
            rng.uniform(-0.004, 0.004),
            rng.uniform(-0.02, 0.02),
        ),
    )


def _ridge(width: int, seed: int, base: float, amplitude: float, octaves: int = 3) -> np.ndarray:
    """A deterministic 1-D silhouette, in pixels from the top."""
    rng = np.random.default_rng(seed)
    x = np.linspace(0.0, 1.0, width, dtype=np.float64)
    out = np.full(width, base, dtype=np.float64)
    for octave in range(octaves):
        frequency = 1.5 * (2 ** octave) + rng.uniform(0.0, 1.5)
        phase = rng.uniform(0.0, 2 * math.pi)
        out += (amplitude / (octave + 1)) * np.sin(2 * math.pi * frequency * x + phase)
    return out


def draw_cartoon_face(draw: ImageDraw.ImageDraw, cx: float, cy: float, r: float,
                      skin: tuple[int, int, int], hair: tuple[int, int, int]) -> None:
    """A drawn cartoon head. NOT a face. See the module docstring.

    Kept deliberately crude: an oval, a hair cap, two eyes with pupils, brows,
    a nose line and a mouth. It has the coarse light/dark structure a
    face detector keys on, which is enough to tell a wired-up detector from an
    unwired one, and nothing like enough to measure one.
    """
    draw.ellipse([cx - r, cy - r * 1.22, cx + r, cy + r * 1.22], fill=skin)
    # hair cap
    draw.chord([cx - r * 1.04, cy - r * 1.34, cx + r * 1.04, cy + r * 0.5],
               start=180, end=360, fill=hair)
    eye_dx, eye_dy, eye_r = r * 0.40, r * 0.22, r * 0.19
    for side in (-1, 1):
        ex = cx + side * eye_dx
        draw.ellipse([ex - eye_r, cy - eye_dy - eye_r * 0.68,
                      ex + eye_r, cy - eye_dy + eye_r * 0.68], fill=(250, 250, 248))
        draw.ellipse([ex - eye_r * 0.42, cy - eye_dy - eye_r * 0.42,
                      ex + eye_r * 0.42, cy - eye_dy + eye_r * 0.42], fill=(32, 26, 24))
        draw.arc([ex - eye_r * 1.2, cy - eye_dy - eye_r * 1.9,
                  ex + eye_r * 1.2, cy - eye_dy - eye_r * 0.2],
                 start=200, end=340, fill=hair, width=max(1, int(r * 0.07)))
    shadow = tuple(max(0, channel - 34) for channel in skin)
    draw.line([cx, cy - r * 0.08, cx, cy + r * 0.24], fill=shadow, width=max(1, int(r * 0.09)))
    draw.arc([cx - r * 0.44, cy + r * 0.16, cx + r * 0.44, cy + r * 0.80],
             start=15, end=165, fill=(126, 62, 58), width=max(1, int(r * 0.10)))


def render(scene: Scene, width: int, height: int) -> Image.Image:
    palette = PALETTES[scene.palette]
    dx = scene.jitter[0] * width
    dy = scene.jitter[1] * height

    # Sky gradient, vectorised: a per-pixel Python loop at 1440x1080 is 1.5M
    # iterations per still and 200 stills would take minutes.
    top = np.array(palette.sky_top, dtype=np.float64)
    bottom = np.array(palette.sky_bottom, dtype=np.float64)
    ramp = np.linspace(0.0, 1.0, height, dtype=np.float64)[:, None]
    canvas = top[None, None, :] * (1.0 - ramp[:, :, None]) + bottom[None, None, :] * ramp[:, :, None]
    canvas = np.repeat(canvas, width, axis=1)

    columns = np.arange(width)[None, :]
    rows = np.arange(height)[:, None]

    # Two ridge lines then the ground, painted back to front.
    horizon_px = scene.horizon * height + dy
    for offset, colour in ((0.10, palette.hill_far), (0.035, palette.hill_near)):
        line = _ridge(width, scene.ridge_seed + int(offset * 1000),
                      horizon_px - offset * height, offset * height * 0.55)
        canvas[rows >= line[None, :]] = np.array(colour, dtype=np.float64)
    ground = np.full(width, horizon_px, dtype=np.float64)
    canvas[rows >= ground[None, :]] = np.array(palette.ground, dtype=np.float64)

    # Sun/lamp: a soft radial falloff, clipped to the sky.
    sun_x = scene.sun_x * width + dx
    sun_y = horizon_px - scene.sun_r * height * 1.4
    sun_r = scene.sun_r * width
    distance = np.sqrt((columns - sun_x) ** 2 + (rows - sun_y) ** 2)
    glow = np.clip(1.0 - distance / (sun_r * 3.2), 0.0, 1.0) ** 2
    canvas += glow[:, :, None] * (np.array(palette.sun, dtype=np.float64) - canvas) * 0.85

    # A large-scale colour cast, unique per scene and SHARED across a burst.
    #
    # This is not decoration. A 64-bit DCT pHash reads only the lowest spatial
    # frequencies, so two scenes that differ mainly in where the small subjects
    # stand can land inside the 4-bit decisive threshold and be merged as
    # duplicates. Measured: two unrelated festival_night stills came out 3 bits
    # apart and dedupe merged them, which would have made the "exactly the
    # declared bursts group" assertion untestable. Modulating the low
    # frequencies directly is what separates them; keying it to `ridge_seed`
    # keeps every frame of a burst identical in exactly the band that decides.
    tint_rng = np.random.default_rng(scene.ridge_seed ^ 0x5EED)
    u = np.linspace(0.0, 1.0, width)[None, :]
    v = np.linspace(0.0, 1.0, height)[:, None]
    cast = np.zeros((height, width), dtype=np.float64)
    for _ in range(2):
        cast += np.sin(
            2 * math.pi * (tint_rng.uniform(0.4, 1.8) * u + tint_rng.uniform(0.4, 1.8) * v)
            + tint_rng.uniform(0.0, 2 * math.pi)
        )
    channel_gain = tint_rng.uniform(-1.0, 1.0, size=3)
    canvas += 13.0 * cast[:, :, None] * channel_gain[None, None, :]

    # Grain, before the subjects so faces stay clean enough to be found at all.
    noise = np.random.default_rng(scene.grain).normal(0.0, 3.0, size=(height, width, 1))
    canvas = canvas + noise
    canvas *= 1.0 + scene.jitter[2]

    image = Image.fromarray(np.clip(canvas, 0, 255).astype(np.uint8), "RGB")
    draw = ImageDraw.Draw(image)

    for sx, sy, scale, skin_idx, hair_idx, shirt_idx in scene.subjects:
        cx = sx * width + dx
        base_y = sy * height + dy
        head_r = scale * height * 0.20
        body_h = head_r * 3.4
        body_w = head_r * 1.9
        draw.rounded_rectangle(
            [cx - body_w / 2, base_y - body_h, cx + body_w / 2, base_y],
            radius=head_r * 0.45, fill=SHIRT_TONES[shirt_idx],
        )
        draw_cartoon_face(draw, cx, base_y - body_h - head_r * 1.05, head_r,
                          SKIN_TONES[skin_idx], HAIR_TONES[hair_idx])

    return image.filter(ImageFilter.GaussianBlur(radius=0.4))


# ---------------------------------------------------------------------------
# Writing stills
# ---------------------------------------------------------------------------


def exif_bytes(*, captured_local: str | None, utc_offset: str | None,
               make: str, model: str,
               lens: str | None, orientation: int) -> bytes | None:
    """Build an EXIF block, or None for a still that must have no EXIF at all.

    Returning None rather than an empty block matters: the ingest worker
    distinguishes "EXIF present but undated" from "no EXIF", and a stray empty
    IFD would make the no-date case untestable.
    """
    if captured_local is None and orientation == 1 and not make:
        return None
    exif = Image.Exif()
    if make:
        exif[TAG_MAKE] = make
    if model:
        exif[TAG_MODEL] = model
    exif[TAG_ORIENTATION] = orientation
    exif[TAG_SOFTWARE] = "memory-engine make_library.py (synthetic)"
    if captured_local is not None:
        exif[TAG_DATETIME] = captured_local
        sub = exif.get_ifd(TAG_EXIF_IFD)
        sub[TAG_DATETIME_ORIGINAL] = captured_local
        sub[TAG_DATETIME_DIGITIZED] = captured_local
        # The offset only means anything alongside a date, so it is written
        # inside this branch. A camera that writes neither leaves the reading
        # zoneless, which is a real state the pipeline must keep distinguishing
        # from "no EXIF at all" and from "dated with a zone".
        if utc_offset:
            sub[TAG_OFFSET_TIME_ORIGINAL] = utc_offset
            sub[TAG_OFFSET_TIME_DIGITIZED] = utc_offset
        if lens:
            sub[TAG_LENS_MODEL] = lens
    return exif.tobytes()


def write_still(path: Path, image: Image.Image, *, exif: bytes | None,
                quality: int, mtime: float) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    kwargs: dict[str, Any] = {"quality": quality, "optimize": True, "progressive": False}
    if exif is not None:
        kwargs["exif"] = exif
    image.save(path, "JPEG", **kwargs)
    os.utime(path, (mtime, mtime))


# ---------------------------------------------------------------------------
# Writing clips
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ClipSpec:
    relpath: str
    width: int
    height: int
    rate: str                  # ffmpeg rate expression, e.g. "30000/1001"
    rate_label: str            # human label, e.g. "29.97"
    duration: float
    scene_key: str
    palette: str
    subjects: int
    timecode: str | None = None
    audio: bool = True
    tone_hz: int = 330
    captured_local: str | None = None
    mtime: float = 0.0
    note: str = ""


def encode_clip(ffmpeg: str, spec: ClipSpec, base: Image.Image, dest: Path) -> None:
    """Encode one clip by panning across a still we drew.

    Panning a 2x drawing is not cinematography, but it produces real inter-frame
    motion, real P-frames and a real variable bitrate, which is what the proxy
    pipeline and any motion signal actually consume. A static image would encode
    to almost nothing and hide every bug that only appears with motion.

    `-fflags +bitexact -flags:v +bitexact` is what makes the output reproducible:
    without it FFmpeg stamps the muxer version and a wall-clock creation time
    into the container, the BLAKE3 changes on every run, and every media_id in
    the library churns.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)
    staging = dest.parent / f".{dest.name}.base.png"
    base.save(staging, "PNG")

    pan = f"(iw-ow)*min(1\\,t/{spec.duration:.3f})"
    tilt = f"(ih-oh)*(0.5+0.35*sin(2*PI*t/{max(spec.duration, 0.001):.3f}))"
    video_filter = (
        f"scale={spec.width * 2}:{spec.height * 2}:flags=bicubic,"
        f"crop={spec.width}:{spec.height}:'{pan}':'{tilt}',"
        f"format=yuv420p"
    )

    command = [
        ffmpeg, "-y", "-hide_banner", "-loglevel", "error", "-nostdin",
        "-loop", "1", "-framerate", spec.rate, "-t", f"{spec.duration}", "-i", str(staging),
    ]
    if spec.audio:
        command += [
            "-f", "lavfi",
            "-i", f"sine=frequency={spec.tone_hz}:sample_rate=48000:duration={spec.duration}",
        ]
    command += [
        "-vf", video_filter,
        "-r", spec.rate,
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "26",
        "-pix_fmt", "yuv420p", "-g", "30",
    ]
    if spec.audio:
        command += ["-c:a", "aac", "-b:a", "96k", "-ar", "48000", "-ac", "1", "-shortest"]
    if spec.timecode:
        command += ["-timecode", spec.timecode]
    command += [
        "-fflags", "+bitexact", "-flags:v", "+bitexact",
        "-movflags", "+faststart",
        "-map_metadata", "-1",
        str(dest),
    ]

    result = subprocess.run(command, capture_output=True, text=True)
    staging.unlink(missing_ok=True)
    if result.returncode != 0:
        raise SystemExit(
            f"ffmpeg failed for {spec.relpath} (exit {result.returncode}):\n"
            f"{result.stderr.strip()}"
        )
    os.utime(dest, (spec.mtime, spec.mtime))


# ---------------------------------------------------------------------------
# The library plan
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Event:
    key: str
    # Short filename code. MUST be unique across events, including events that
    # share a folder -- two events in one folder generating IMG_GO0006.JPG each
    # means the second silently overwrites the first, and the only visible
    # symptom is a file count that nobody checks. `plan_stills` asserts it.
    code: str
    folder: str
    palette: str
    start: datetime
    interval_s: int
    make: str
    model: str
    lens: str | None
    weight: int          # share of the filler stills
    # The zone this camera stamped alongside DateTimeOriginal, or None for a
    # body that writes none. Every event here happened in India, so a camera
    # that writes an offset writes "+05:30"; the 2019 Canon does not, because
    # OffsetTimeOriginal is EXIF 2.31 and plenty of bodies of that generation
    # never wrote it. That asymmetry is the point: a library where every file
    # is dated cannot exercise the code that refuses to invent a zone.
    utc_offset: str | None = None


EVENTS: tuple[Event, ...] = (
    Event("goa_2019", "GOA", "2019-03 Goa", "beach_noon",
          datetime(2019, 3, 12, 9, 40, 0), 47,
          "Canon", "Canon EOS R6", "RF24-105mm F4 L IS USM", 5),
    Event("goa_2019_sunset", "SUN", "2019-03 Goa", "beach_sunset",
          datetime(2019, 3, 12, 18, 5, 0), 23,
          "Canon", "Canon EOS R6", "RF24-105mm F4 L IS USM", 3),
    Event("diwali_2021", "DIW", "2021-11 Diwali", "festival_night",
          datetime(2021, 11, 4, 19, 30, 0), 31,
          "Google", "Pixel 6", None, 5, "+05:30"),
    Event("hills_2023", "HIL", "2023-06 Hills", "hill_morning",
          datetime(2023, 6, 12, 7, 15, 0), 61,
          "Apple", "iPhone 14 Pro", "iPhone 14 Pro back triple camera", 5,
          "+05:30"),
    Event("kitchen_2023", "KIT", "2023-06 Hills", "indoor_warm",
          datetime(2023, 6, 12, 20, 40, 0), 37,
          "Apple", "iPhone 14 Pro", "iPhone 14 Pro back triple camera", 2,
          "+05:30"),
)

LANDSCAPE = (1440, 1080)
PORTRAIT = (1080, 1440)


@dataclass
class PlannedStill:
    relpath: str
    event: Event
    index: int
    size: tuple[int, int]
    subjects: int
    captured_local: str | None
    mtime_dt: datetime
    orientation: int = 1
    quality: int = 88
    write_exif: bool = True
    burst_id: str | None = None
    burst_frame: int = 0
    tags: tuple[str, ...] = ()


def epoch(when: datetime) -> float:
    """Treat the naive wall-clock reading as UTC for the filesystem stamp.

    Real cameras write a wall-clock reading with no zone, and the pipeline is
    not allowed to invent one. Using UTC here keeps the *generator*
    reproducible on any host; it is not a claim about where the photo was
    taken, and nothing downstream should read it as one.
    """
    return when.replace(tzinfo=timezone.utc).timestamp()


def exif_string(when: datetime) -> str:
    return when.strftime("%Y:%m:%d %H:%M:%S")


def plan_stills(seed: int, total: int) -> list[PlannedStill]:
    """Lay out every still, specials first, then fillers to reach `total`."""
    planned: list[PlannedStill] = []
    counters: dict[str, int] = {event.key: 0 for event in EVENTS}
    by_key = {event.key: event for event in EVENTS}

    def next_index(key: str) -> int:
        counters[key] += 1
        return counters[key]

    def add(event_key: str, *, size=LANDSCAPE, subjects: int | None = None,
            orientation: int = 1, offset_s: int | None = None,
            mtime_shift: timedelta = timedelta(0), write_exif: bool = True,
            captured: bool = True, name: str | None = None,
            burst_id: str | None = None, burst_frame: int = 0,
            tags: tuple[str, ...] = (), quality: int = 88) -> PlannedStill:
        event = by_key[event_key]
        index = next_index(event_key)
        rng = stream(seed, "still", event_key, index)
        when = event.start + timedelta(
            seconds=event.interval_s * index if offset_s is None else offset_s
        )
        still = PlannedStill(
            relpath=f"{event.folder}/{name or f'IMG_{event.code}{index:04d}.JPG'}",
            event=event,
            index=index,
            size=size,
            subjects=rng.randrange(0, 4) if subjects is None else subjects,
            captured_local=exif_string(when) if captured else None,
            mtime_dt=when + mtime_shift,
            orientation=orientation,
            quality=quality,
            write_exif=write_exif,
            burst_id=burst_id,
            burst_frame=burst_frame,
            tags=tags,
        )
        planned.append(still)
        return still

    # --- the cases that break things ------------------------------------
    # Burst of five: the shutter held down for four seconds.
    for frame in range(5):
        add("goa_2019_sunset", subjects=2, offset_s=600 + frame,
            name=f"IMG_SUNSET_BURST_{frame + 1}.JPG",
            burst_id="burst_goa_sunset", burst_frame=frame,
            tags=("near_duplicate_burst",))
    # A second, shorter burst, in a completely different scene, so a threshold
    # that merges the two bursts together is visible as a failure.
    for frame in range(4):
        add("diwali_2021", subjects=3, offset_s=1200 + frame,
            name=f"IMG_DIYA_BURST_{frame + 1}.JPG",
            burst_id="burst_diwali_diya", burst_frame=frame,
            tags=("near_duplicate_burst",))

    # EXIF says 2023, the filesystem says 2026: copied off an old drive.
    for offset in range(8):
        add("hills_2023", offset_s=3000 + offset * 90,
            mtime_shift=timedelta(days=1050, hours=6),
            name=f"IMG_COPIED_{offset + 1:02d}.JPG",
            tags=("exif_mtime_disagreement",))

    # No EXIF at all, and a filename no date pattern matches.
    add("hills_2023", captured=False, write_exif=False, name="scan_0043.jpg",
        subjects=1, tags=("no_exif_date", "no_filename_date"))
    # No EXIF, but a WhatsApp filename the ingest worker can date to a day.
    add("diwali_2021", captured=False, write_exif=False,
        name="IMG-20211104-WA0009.jpg", subjects=2,
        tags=("no_exif_date", "filename_dated"))
    # EXIF orientation 6: stored landscape, displayed portrait.
    add("goa_2019", orientation=6, subjects=2, name="IMG_ROTATED_90.JPG",
        tags=("orientation_6",))
    # Portrait framing, ordinary.
    add("kitchen_2023", size=PORTRAIT, subjects=1, name="IMG_PORTRAIT_01.JPG",
        tags=("portrait",))
    # A heavily recompressed copy of nothing in particular: low quality, so the
    # quality stack has one obviously bad frame to rank last.
    add("kitchen_2023", quality=22, subjects=2, name="IMG_LOWQ_01.JPG",
        tags=("low_quality",))

    # --- fillers ---------------------------------------------------------
    remaining = total - len(planned)
    if remaining < 0:
        raise SystemExit(
            f"--stills {total} is below the {len(planned)} stills the edge cases need"
        )
    order: list[str] = []
    for event in EVENTS:
        order.extend([event.key] * event.weight)
    for position in range(remaining):
        add(order[position % len(order)])

    # Two plans that resolve to one path means one file on disk and two
    # manifest entries, one of which points at bytes that no longer exist.
    # Found exactly that way: `goa_2019` and `goa_2019_sunset` share a folder
    # and both derived their prefix from the first two letters of the key, so
    # 27 stills were overwritten and the manifest claimed 215 files for 188.
    seen: dict[str, str] = {}
    for still in planned:
        clash = seen.get(still.relpath)
        if clash is not None:
            raise SystemExit(
                f"two stills plan to write {still.relpath} "
                f"({clash} and {still.event.key}); Event.code must be unique"
            )
        seen[still.relpath] = still.event.key
    return planned


def plan_clips(seed: int, count: int) -> list[ClipSpec]:
    """Video, including the GoPro chapter spans.

    The GoPro names follow `workers/ingest/src/gopro.rs::parse_filename`
    exactly, and the two families there use DIFFERENT index conventions:

      GX/GH:  GX<CC><RRRR>.MP4  -> chapter index = CC - 1, so GX010012 is
              index 0 and GX020012 is index 1. Chapter 00 is rejected.
      legacy: GOPR<RRRR>.MP4    -> index 0
              GP<CC><RRRR>.MP4  -> index = CC, so GP010044 is index 1 and
              follows GOPR0044.

    Both are generated because getting the second one wrong produces a span
    that starts at index 1 with no index 0, which the assembler treats as
    incomplete -- a failure that looks exactly like "the first chapter is
    missing from disk".

    Every member of a span is given DIFFERENT content on purpose. Identical
    chapters would collide on BLAKE3, and gopro.rs skips assembly for a group
    that "repeats the same content at multiple indexes" -- so a library of
    identical chapters would silently test nothing.
    """
    gopro_start = datetime(2023, 6, 12, 11, 0, 0)
    chapter_s = 5.0
    specs: list[ClipSpec] = [
        ClipSpec(
            relpath=f"GoPro/GX0{chapter + 1}0012.MP4",
            width=1920, height=1080, rate="30", rate_label="30",
            duration=chapter_s, scene_key=f"gopro_gx_{chapter}",
            palette="hill_morning", subjects=1 + chapter,
            timecode=f"00:00:{int(chapter * chapter_s):02d}:00",
            tone_hz=220 + 40 * chapter,
            mtime=epoch(gopro_start + timedelta(seconds=chapter * chapter_s)),
            note="GoPro GX chapter span, member index %d" % chapter,
        )
        for chapter in range(3)
    ]
    legacy_start = datetime(2023, 6, 12, 15, 20, 0)
    specs += [
        ClipSpec("GoPro/GOPR0044.MP4", 1920, 1080, "30", "30", chapter_s,
                 "gopro_legacy_0", "hill_morning", 2, timecode="00:00:00:00",
                 tone_hz=300, mtime=epoch(legacy_start),
                 note="legacy GoPro span, member index 0"),
        ClipSpec("GoPro/GP010044.MP4", 1920, 1080, "30", "30", chapter_s,
                 "gopro_legacy_1", "hill_morning", 3, timecode="00:00:05:00",
                 tone_hz=340, mtime=epoch(legacy_start + timedelta(seconds=chapter_s)),
                 note="legacy GoPro span, member index 1"),
        ClipSpec("2023-06 Hills/VID_20230612_101533.mp4", 1920, 1080,
                 "30000/1001", "29.97", 4.0, "hills_29_97", "hill_morning", 2,
                 tone_hz=392, mtime=epoch(datetime(2023, 6, 12, 10, 15, 33)),
                 note="horizontal, 29.97 fps (the rate that breaks integer frame math)"),
        ClipSpec("2024-02 WhatsApp/VID-20240203-WA0007.mp4", 1080, 1920,
                 "30", "30", 4.0, "whatsapp_vertical", "indoor_warm", 1,
                 tone_hz=294, mtime=epoch(datetime(2024, 2, 3, 21, 12, 0)),
                 note="vertical 9:16, WhatsApp filename convention"),
        ClipSpec("2021-11 Diwali/VID_20211107_204411.mp4", 1280, 720,
                 "24", "24", 4.0, "diwali_24", "festival_night", 3,
                 tone_hz=247, mtime=epoch(datetime(2021, 11, 7, 20, 44, 11)),
                 note="24 fps, 720p"),
        ClipSpec("2021-11 Diwali/VID_20211107_205002.mp4", 1920, 1080,
                 "60", "60", 3.0, "diwali_60", "festival_night", 2,
                 tone_hz=523, mtime=epoch(datetime(2021, 11, 7, 20, 50, 2)),
                 note="60 fps"),
        ClipSpec("2019-03 Goa/VID_20190312_173010.mp4", 1920, 1080,
                 "25", "25", 4.0, "goa_25", "beach_sunset", 2, audio=False,
                 mtime=epoch(datetime(2019, 3, 12, 17, 30, 10)),
                 note="25 fps, NO audio track (the ambient-music path must cope)"),
    ]
    if count > len(specs):
        raise SystemExit(
            f"--clips {count} exceeds the {len(specs)} defined clips; add specs first"
        )
    return specs[:count]


# ---------------------------------------------------------------------------
# Deliberately broken files
# ---------------------------------------------------------------------------


def write_broken(out: Path, healthy_jpeg: bytes,
                 healthy_mp4: bytes) -> list[dict[str, Any]]:
    """Files that must fail LOUDLY.

    "Loudly" is the whole point. A pipeline that skips a corrupt file without
    saying so loses a photograph and reports success; the ingest worker
    quarantines instead, and a demo has to be able to check that it did.
    """
    entries: list[dict[str, Any]] = []
    folder = out / "Broken"
    folder.mkdir(parents=True, exist_ok=True)
    stamp = epoch(datetime(2023, 6, 12, 23, 0, 0))

    # Two truncated JPEGs, at two depths, because one of them is a POSITIVE
    # CONTROL and the other is the case that actually matters.
    #
    # 512 bytes stops before the start-of-scan marker, so no decoder can even
    # begin, and the ingest worker quarantines it. That is the control: if this
    # one is not quarantined, quarantine is broken outright and every other
    # result here is suspect.
    #
    # A third of the file has the full header and a third of the entropy data.
    # The Rust `image` crate decodes it anyway and returns a partly-grey
    # picture, so at the time of writing the ingest worker files it as
    # state=proxied with a pHash and a thumbnail -- a mangled photograph
    # entering the library indistinguishable from a good one. The contract says
    # otherwise: contracts/fixtures/media-record/valid/file-truncated-quarantined.json
    # is quarantined with kind=unknown. The expectation below is the contract's,
    # so a consumer that checks it reports a real defect rather than agreeing
    # with the bug.
    (folder / "IMG_HEADER_ONLY.JPG").write_bytes(healthy_jpeg[:512])
    entries.append({
        "relpath": "Broken/IMG_HEADER_ONLY.JPG",
        "kind": "broken",
        "expect": "quarantine",
        "expect_detail": "512 bytes: truncated before the start-of-scan marker",
        "control": "positive",
        "note": "positive control -- if this is not quarantined, quarantine is broken",
    })
    (folder / "IMG_TRUNCATED.JPG").write_bytes(
        healthy_jpeg[: max(2048, len(healthy_jpeg) // 3)]
    )
    entries.append({
        "relpath": "Broken/IMG_TRUNCATED.JPG",
        "kind": "broken",
        "expect": "quarantine",
        "expect_detail": "one third of a JPEG: header parses, most scan data is gone",
        "known_gap": (
            "workers/ingest decodes with the `image` crate, which tolerates "
            "this and yields a partly-grey picture; the record comes back "
            "state=proxied instead of quarantined"
        ),
        "note": "the case that matters: silently accepted today",
    })

    # A zero-byte file, which is what an interrupted copy leaves behind.
    (folder / "IMG_ZERO_BYTES.JPG").write_bytes(b"")
    entries.append({
        "relpath": "Broken/IMG_ZERO_BYTES.JPG",
        "kind": "broken",
        "expect": "quarantine",
        "expect_detail": "zero bytes",
        "note": "what an interrupted copy leaves behind",
    })

    # An MP4 cut after the header: ftyp is present so it is detected as video,
    # but no decoder can open it. Ingest only hashes videos, so this one has to
    # fail at the proxy stage rather than at scan.
    (folder / "VID_TRUNCATED.MP4").write_bytes(healthy_mp4[: min(8192, len(healthy_mp4))])
    entries.append({
        "relpath": "Broken/VID_TRUNCATED.MP4",
        "kind": "broken",
        "expect": "proxy_failure",
        "expect_detail": "ftyp present, moov absent; scan hashes it, proxy must fail",
        "note": "ingest does not decode video at scan time, so this survives scan",
    })

    # Strays every real library has.
    (folder / "notes.txt").write_text(
        "Not media. Every real library has one of these.\n", encoding="utf-8"
    )
    entries.append({
        "relpath": "Broken/notes.txt",
        "kind": "stray",
        "expect": "quarantine",
        "expect_detail": "unsupported format (no recognised signature)",
        "note": "a stray text file",
    })
    (folder / "IMG_SIDECAR.xmp").write_text(
        '<?xml version="1.0"?><x:xmpmeta xmlns:x="adobe:ns:meta/"/>\n', encoding="utf-8"
    )
    entries.append({
        "relpath": "Broken/IMG_SIDECAR.xmp",
        "kind": "stray",
        "expect": "quarantine",
        "expect_detail": "unsupported format (XMP sidecar)",
        "note": "sidecar with no adopting parent in this folder",
    })

    for entry in entries:
        os.utime(out / entry["relpath"], (stamp, stamp))
    return entries


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------


def blake3_hex(path: Path) -> str:
    """The media_id the ingest worker will derive for this file.

    Plain BLAKE3 over the file bytes -- see `read_source_once` in
    workers/ingest/src/media.rs. Recording it here lets a consumer assert
    against identities instead of matching on filenames, which is what makes
    the expectations below checkable rather than decorative.
    """
    try:
        import blake3
    except ImportError:
        return ""
    hasher = blake3.blake3()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def reconcile(out: Path, files: Sequence[dict[str, Any]]) -> None:
    """Fail if the manifest and the directory disagree in any direction.

    Three separate ways to lie, all of which have to be impossible:
      * a manifest entry with no file  -- something overwrote or deleted it
      * a file with no manifest entry  -- something wrote outside the plan
      * a recorded BLAKE3 that no longer matches the bytes -- a later write
        landed on an earlier file's path, which is the collision case
    """
    expected = {
        entry["relpath"]: entry for entry in files if entry.get("generated", True)
    }
    on_disk = {
        str(path.relative_to(out)) for path in out.rglob("*")
        if path.is_file() and path.name != MANIFEST_NAME
    }

    problems: list[str] = []
    if len(expected) != len([e for e in files if e.get("generated", True)]):
        problems.append("duplicate relpaths in the plan")
    for missing in sorted(set(expected) - on_disk):
        problems.append(f"manifest lists {missing}, which is not on disk")
    for extra in sorted(on_disk - set(expected)):
        problems.append(f"{extra} is on disk but not in the manifest")
    for relpath, entry in sorted(expected.items()):
        digest = entry.get("blake3")
        if not digest or relpath not in on_disk:
            continue
        actual = blake3_hex(out / relpath)
        if actual and actual != digest:
            problems.append(
                f"{relpath} hashes to {actual[:12]} but the manifest says {digest[:12]}"
            )

    if problems:
        raise SystemExit(
            "generated library does not match its own manifest:\n  "
            + "\n  ".join(problems[:20])
            + (f"\n  ... and {len(problems) - 20} more" if len(problems) > 20 else "")
        )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--out", type=Path, required=True, help="destination directory")
    parser.add_argument("--seed", type=int, default=20260817)
    parser.add_argument("--stills", type=int, default=200)
    parser.add_argument("--clips", type=int, default=10)
    parser.add_argument("--force", action="store_true",
                        help="replace an existing generated library")
    parser.add_argument("--ffmpeg", default=os.environ.get("MEMORY_ENGINE_FFMPEG", "ffmpeg"))
    parser.add_argument("--no-video", action="store_true",
                        help="stills only; the manifest records the clips as NOT GENERATED")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    out = args.out.expanduser().resolve()
    check_destination(out, args.force)

    def say(message: str) -> None:
        if not args.quiet:
            print(message, flush=True)

    ffmpeg = shutil.which(args.ffmpeg) if not args.no_video else None
    video_skipped_reason = None
    if args.no_video:
        video_skipped_reason = "--no-video was passed"
    elif ffmpeg is None:
        # Not a warning buried in the output: the library is materially
        # different without clips, and the manifest has to say so.
        video_skipped_reason = f"ffmpeg not found on PATH (looked for {args.ffmpeg!r})"

    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    files: list[dict[str, Any]] = []

    # --- stills ----------------------------------------------------------
    planned = plan_stills(args.seed, args.stills)
    say(f"  stills   {len(planned)} ...")
    scene_cache: dict[str, Scene] = {}
    for position, still in enumerate(planned):
        if still.burst_id:
            base = scene_cache.get(still.burst_id)
            if base is None:
                base = build_scene(
                    stream(args.seed, "burst", still.burst_id),
                    still.event.palette, still.subjects,
                )
                scene_cache[still.burst_id] = base
            scene = jittered(
                base, still.burst_frame,
                stream(args.seed, "burst-jitter", still.burst_id, still.burst_frame),
            )
        else:
            scene = build_scene(
                stream(args.seed, "scene", still.relpath),
                still.event.palette, still.subjects,
            )
        image = render(scene, *still.size)
        exif = (
            exif_bytes(
                captured_local=still.captured_local,
                utc_offset=still.event.utc_offset,
                make=still.event.make, model=still.event.model,
                lens=still.event.lens, orientation=still.orientation,
            )
            if still.write_exif else None
        )
        path = out / still.relpath
        write_still(path, image, exif=exif, quality=still.quality,
                    mtime=epoch(still.mtime_dt))
        files.append({
            "relpath": still.relpath,
            "kind": "still",
            "blake3": blake3_hex(path),
            "byte_size": path.stat().st_size,
            "stored_size": {"width": still.size[0], "height": still.size[1]},
            "orientation": still.orientation,
            "event": still.event.key,
            "exif_datetime_original": still.captured_local,
            # None means the file carries a wall-clock reading with no zone, so
            # `captured_at.utc` MUST stay null on the resulting MediaRecord. A
            # consumer that finds a utc against a null offset here has found
            # the pipeline inventing a zone.
            "exif_offset_time_original": (
                still.event.utc_offset if still.captured_local else None
            ),
            "has_exif": exif is not None,
            "filesystem_mtime_utc": datetime.fromtimestamp(
                epoch(still.mtime_dt), timezone.utc
            ).isoformat().replace("+00:00", "Z"),
            "burst_id": still.burst_id,
            "tags": list(still.tags),
        })
        if not args.quiet and (position + 1) % 50 == 0:
            say(f"           {position + 1}/{len(planned)}")

    # --- clips -----------------------------------------------------------
    clip_specs = plan_clips(args.seed, args.clips)
    if video_skipped_reason:
        say(f"  clips    SKIPPED — {video_skipped_reason}")
        for spec in clip_specs:
            files.append({
                "relpath": spec.relpath,
                "kind": "clip",
                "generated": False,
                "skipped_reason": video_skipped_reason,
                "note": spec.note,
            })
    else:
        say(f"  clips    {len(clip_specs)} ...")
        for spec in clip_specs:
            scene = build_scene(
                stream(args.seed, "clip", spec.scene_key), spec.palette, spec.subjects
            )
            base = render(scene, spec.width * 2, spec.height * 2)
            path = out / spec.relpath
            encode_clip(ffmpeg, spec, base, path)
            files.append({
                "relpath": spec.relpath,
                "kind": "clip",
                "generated": True,
                "blake3": blake3_hex(path),
                "byte_size": path.stat().st_size,
                "stored_size": {"width": spec.width, "height": spec.height},
                "frame_rate": spec.rate_label,
                "duration_s": spec.duration,
                "has_audio": spec.audio,
                "start_timecode": spec.timecode,
                "note": spec.note,
            })

    # --- broken ----------------------------------------------------------
    # Truncations are taken from real generated bytes so the headers are real.
    healthy_jpeg = (out / planned[0].relpath).read_bytes()
    healthy_mp4 = b""
    if not video_skipped_reason:
        healthy_mp4 = (out / clip_specs[0].relpath).read_bytes()
    else:
        # Without ffmpeg there is no MP4 to truncate. Say so rather than
        # writing a fake one that would test the wrong failure.
        say("  broken   MP4 truncation SKIPPED — no clip was generated to truncate")
    broken = write_broken(out, healthy_jpeg, healthy_mp4)
    for entry in broken:
        if entry["relpath"].endswith(".MP4") and video_skipped_reason:
            entry["generated"] = False
            entry["skipped_reason"] = "no MP4 existed to truncate"
            entry["expect"] = "not_generated"
            (out / entry["relpath"]).unlink(missing_ok=True)
            continue
        path = out / entry["relpath"]
        entry["blake3"] = blake3_hex(path)
        entry["byte_size"] = path.stat().st_size
    files.extend(broken)

    # --- reconcile the plan against the disk -----------------------------
    # A manifest that describes files which are not there is worse than no
    # manifest: every consumer downstream asserts against a fiction. This is
    # the check that caught the filename collision above, so it stays.
    reconcile(out, files)

    # --- manifest --------------------------------------------------------
    by_relpath = {entry["relpath"]: entry for entry in files}

    bursts: dict[str, list[str]] = {}
    for entry in files:
        if entry.get("burst_id"):
            bursts.setdefault(entry["burst_id"], []).append(entry["relpath"])

    spans = [
        {
            "span_kind": "gopro_chapter",
            "family": "gx",
            "recording": "0012",
            "members": [f"GoPro/GX0{n + 1}0012.MP4" for n in range(3)],
            "expected_indexes": [0, 1, 2],
        },
        {
            "span_kind": "gopro_chapter",
            "family": "legacy",
            "recording": "0044",
            "members": ["GoPro/GOPR0044.MP4", "GoPro/GP010044.MP4"],
            "expected_indexes": [0, 1],
        },
    ]
    for span in spans:
        span["members"] = [m for m in span["members"] if m in by_relpath]
        span["member_blake3"] = [by_relpath[m].get("blake3", "") for m in span["members"]]
        span["generated"] = all(by_relpath[m].get("generated", True) for m in span["members"])

    generated_count = sum(1 for e in files if e.get("generated", True))
    manifest = {
        "generator": "scripts/demo/make_library.py",
        "generator_version": GENERATOR_VERSION,
        "seed": args.seed,
        "synthetic": True,
        "disclaimer": (
            "Every file here is drawn or encoded from scratch. The faces are "
            "cartoons and prove nothing about detection quality; no quality, "
            "aesthetic or face metric measured on this library is meaningful. "
            "See the module docstring of make_library.py."
        ),
        "counts": {
            "stills": sum(1 for e in files if e["kind"] == "still"),
            "clips": sum(1 for e in files if e["kind"] == "clip"),
            "clips_generated": sum(
                1 for e in files if e["kind"] == "clip" and e.get("generated")
            ),
            "broken": sum(1 for e in files if e["kind"] == "broken"),
            "strays": sum(1 for e in files if e["kind"] == "stray"),
            "files_on_disk": generated_count,
        },
        "skipped": ([] if not video_skipped_reason else [{
            "what": "video clips and the truncated MP4",
            "reason": video_skipped_reason,
            "consequence": (
                "no video, no GoPro spans, no frame-rate coverage, and the "
                "proxy stage has nothing to fail on"
            ),
        }]),
        "expectations": {
            "near_duplicate_bursts": [
                {"burst_id": burst, "members": sorted(members),
                 "member_blake3": [by_relpath[m]["blake3"] for m in sorted(members)]}
                for burst, members in sorted(bursts.items())
            ],
            "no_exif_date": [
                e["relpath"] for e in files if "no_exif_date" in e.get("tags", [])
            ],
            "unknown_capture_time": [
                e["relpath"] for e in files if "no_filename_date" in e.get("tags", [])
            ],
            "filename_dated": [
                e["relpath"] for e in files if "filename_dated" in e.get("tags", [])
            ],
            "exif_mtime_disagreement": [
                {
                    "relpath": e["relpath"],
                    "exif_datetime_original": e["exif_datetime_original"],
                    "filesystem_mtime_utc": e["filesystem_mtime_utc"],
                }
                for e in files if "exif_mtime_disagreement" in e.get("tags", [])
            ],
            "orientation_6": [
                e["relpath"] for e in files if "orientation_6" in e.get("tags", [])
            ],
            "gopro_spans": spans,
            "must_quarantine": [
                {
                    "relpath": e["relpath"],
                    "why": e["expect_detail"],
                    **({"control": e["control"]} if e.get("control") else {}),
                    **({"known_gap": e["known_gap"]} if e.get("known_gap") else {}),
                }
                for e in files if e.get("expect") == "quarantine"
            ] + [
                # The manifest sits inside the library so a consumer can find
                # it without being told where it is. The scanner therefore
                # walks it, cannot identify it, and quarantines it -- which is
                # correct behaviour and is declared here so it does not read as
                # an unexplained extra quarantine.
                {"relpath": MANIFEST_NAME,
                 "why": "the manifest itself: not media, no recognised signature"}
            ],
            "must_fail_at_proxy": [
                {"relpath": e["relpath"], "why": e["expect_detail"]}
                for e in files if e.get("expect") == "proxy_failure"
            ],
            "frame_rates": sorted({
                e["frame_rate"] for e in files if e.get("frame_rate")
            }),
            "vertical_clips": [
                e["relpath"] for e in files
                if e.get("kind") == "clip" and e.get("generated")
                and e["stored_size"]["height"] > e["stored_size"]["width"]
            ],
            "silent_clips": [
                e["relpath"] for e in files
                if e.get("kind") == "clip" and e.get("generated") and not e["has_audio"]
            ],
        },
        "not_represented": [
            "real photographic content of any kind",
            "real faces -- the drawn ones are cartoons (see disclaimer)",
            "HEIC/HEIF, RAW, Live Photos, or any Apple/Android container",
            "real sensor noise, motion blur, lens character, JPEG generation loss",
            "GPS, altitude, or any location metadata",
            "audio worth analysing: the tracks are sine tones, not music or speech",
            "hardware-encoder quirks: everything is libx264 at one preset",
            "libraries at scale -- 200 stills is not 3TB, and nothing here "
            "exercises the resumable-scan or I/O-saturation paths",
        ],
        "files": files,
    }
    (out / MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, sort_keys=False) + "\n", encoding="utf-8"
    )

    counts = manifest["counts"]
    say("")
    say(f"  library  {out}")
    say(f"           {counts['stills']} stills, "
        f"{counts['clips_generated']}/{counts['clips']} clips, "
        f"{counts['broken']} broken, {counts['strays']} strays")
    if manifest["skipped"]:
        for skip in manifest["skipped"]:
            say(f"  SKIPPED  {skip['what']} — {skip['reason']}")
            say(f"           consequence: {skip['consequence']}")
        say("  NOT a complete library. Exit code 2.")
        return 2
    say(f"  manifest {out / MANIFEST_NAME}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
