"""A folder of clips in, a reel EDL, a film EDL, and playable files out.

WHAT THESE TESTS ARE ACTUALLY DEFENDING

The story stage is the one place in this pipeline where a plausible, entirely
wrong result is easy to produce and nearly impossible to spot: a reel renders,
it looks like a reel, and the only way to find out that its features were
invented or its cuts landed in the wrong second is to watch it against the
source. So the assertions are about ABSENCES and IDENTITIES, not about the run
returning something:

  * every feature no producer measured is ABSENT from the MomentRecords, not
    zero. A zero is a measurement nobody took;
  * the run REPORTS that no cut is beat-locked and no cut is certified
    word-safe, because both are what a reader would otherwise assume;
  * the EDL's `edl_id` is stable across runs over an unchanged library, which is
    what makes it usable as the render cache key;
  * a source at a different frame rate is excluded and COUNTED, not quietly
    dropped into a timeline whose rate it does not share;
  * the stage emits TWO plans, and the film is REFUSED rather than faked when
    the footage cannot fill three acts. `StoryStage` below runs on a library
    that yields two moments and asserts the refusal; `FilmFromTheLibrary` runs
    on one that yields enough and asserts the film all the way to a file.

Everything is real: the Rust ingest worker makes the proxies, FFmpeg decodes
them, `plan_moments`, `plan_reel` and `plan_film` are the shipped planners, and
the render tests encode actual files. The clips are generated by FFmpeg rather
than committed, and the user's own photographs are never involved.
"""

from __future__ import annotations

import json
import shutil
import tempfile
import unittest
from pathlib import Path

from support import (  # noqa: E402
    require_ffmpeg,
    require_ingest_binary,
    write_clip,
)

from memory_engine_pipeline.runner import run_pipeline  # noqa: E402
from memory_engine_pipeline.stages.base import Settings, StageStatus  # noqa: E402

# Producers that do not exist. Every one of them is a feature `plan_moments`
# would use and cannot, and the point of naming them here is that the day one
# lands, this list is what has to change.
UNMEASURED = ("face_presence", "max_face_area_ratio", "smile_intensity")


def _stage(report, name):
    for result in report.results:
        if result.stage == name:
            return result
    raise AssertionError(f"{name} did not run")


def _library(root: Path) -> None:
    """Three clips: two at 30 fps and one at 24, so a rate split is exercised."""
    write_clip(root / "VID_0001.mp4", seconds=2.0, rate=30)
    write_clip(root / "VID_0002.mp4", seconds=2.0, rate=30, tone_hz=660)
    write_clip(root / "VID_0003.mp4", seconds=2.0, rate=24, tone_hz=220)


class StoryStage(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        require_ingest_binary()
        require_ffmpeg()
        cls.root = Path(tempfile.mkdtemp(prefix="mep-story-src-"))
        cls.workdir = Path(tempfile.mkdtemp(prefix="mep-story-work-"))
        _library(cls.root)
        cls.report = run_pipeline(
            [cls.root],
            cls.workdir,
            stages=["ingest", "story"],
            settings=Settings(render_print=False, render_video=False, reel_seconds=6.0),
        )
        cls.story = _stage(cls.report, "story")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.root, ignore_errors=True)
        shutil.rmtree(cls.workdir, ignore_errors=True)

    def test_the_stage_completes_and_names_an_edl(self):
        self.assertEqual(
            StageStatus.COMPLETED, self.story.status, self.story.detail
        )
        self.assertEqual(1, len(self.story.outputs))
        self.assertTrue(Path(self.story.outputs[0]).is_file())

    def test_a_library_too_thin_for_three_acts_refuses_the_film(self):
        """Two 2-second clips at the timeline rate yield two moments, and a
        three-act film needs a shot in each act. The stage reports the planner's
        own refusal rather than emitting a two-shot artifact labelled a film --
        which is the relabelling this stage has refused to do since before a
        film planner existed."""
        self.assertIn("no film planned", self.story.counts["film"])
        self.assertIn("three-act", self.story.counts["film"])
        self.assertIn("no film planned", self.story.detail)
        self.assertEqual(
            ["reel"],
            [
                json.loads(Path(path).read_text(encoding="utf-8"))["kind"]
                for path in self.story.outputs
            ],
        )

    def test_every_clip_got_a_proxy_and_a_score(self):
        proxies = self.story.counts["proxies"]
        moments = self.story.counts["moments"]
        self.assertEqual(3, proxies["done"] + proxies["already"], proxies)
        self.assertEqual(0, proxies["failed"], proxies)
        self.assertEqual(3, moments["scored"] + moments["already"], moments)
        self.assertGreater(moments["kept"], 0, "no moment survived scoring")

    def test_the_run_reports_that_no_cut_is_beat_locked(self):
        """The single most plausible wrong assumption about a reel.

        `music/library.json` bundles no audio, so there is no track to
        beat-detect and no `BeatGrid`. A reel whose cuts fall on a synthetic
        tick grid is a different product from one cut to music, and nothing in
        the file says which one it is.
        """
        reel = self.story.counts["reel"]
        self.assertGreater(reel["clips"], 0)
        self.assertEqual(0, reel["beat_locked"])
        self.assertIn("beat-locked", self.story.detail)

        edl = json.loads(Path(self.story.outputs[0]).read_text(encoding="utf-8"))
        self.assertIsNone(edl["beat_grid"])
        for track in edl["tracks"]:
            for item in track["items"]:
                if item["item_type"] == "clip":
                    self.assertIsNone(item["beat_lock"])

    def test_the_run_reports_that_no_cut_is_certified_word_safe(self):
        """No transcript backend exists, so word timings are UNKNOWN.

        Not "the cuts are unsafe" and not "the cuts are safe" -- unknown. The
        planner emits its `no_mid_word_cut` finding only when it has words, so
        the EDL carries no such finding at all, and the stage has to be the
        thing that says so.
        """
        self.assertEqual(0, self.story.counts["reel"]["word_safe_cuts_certified"])
        self.assertIn("word-safe", self.story.detail)
        edl = json.loads(Path(self.story.outputs[0]).read_text(encoding="utf-8"))
        ids = {check["check_id"] for check in edl["validation"]["checks"]}
        self.assertNotIn("no_mid_word_cut", ids)

    def test_features_nobody_measured_are_absent_rather_than_zero(self):
        from memory_engine_media_db import Database  # noqa: PLC0415

        database = Database.open(self.workdir / "library.db")
        try:
            moments = database.best_moments(limit=200)
            self.assertTrue(moments, "no MomentRecord reached the database")
            for record in moments:
                features = record.get("features") or {}
                for name in UNMEASURED:
                    self.assertNotIn(name, features, f"{name} was invented")
                # And what WAS measured is there, so the absence above is a
                # statement about the missing producers rather than about a
                # feature block that never got written.
                self.assertIn("motion_energy", features)
                self.assertIn("sharpness", features)
        finally:
            database.close()

    def test_a_source_at_another_rate_is_excluded_and_counted(self):
        """An EDL has ONE timeline rate and the renderer refuses a source at
        any other rather than resampling it. Dropping the odd clip silently is
        how a library quietly loses a third of itself."""
        reel = self.story.counts["reel"]
        self.assertEqual(2, reel["sources"])
        self.assertEqual(1, reel["sources_excluded"])
        self.assertEqual(30.0, reel["rate"])

    def test_the_render_target_is_the_measured_source_and_not_the_proxy(self):
        """The target is `MediaRecord.video.oriented_size`, not the 480p raster.

        `workers/ingest` measures the source's displayed geometry (issue #78),
        so the plan no longer falls back to the only picture the library had
        decoded for itself. The clips here are 640x360 and their proxies are
        854x480: asserting the target is 640x360 is asserting that the number
        came from the SOURCE, because the fallback would give the larger one.
        """
        reel = self.story.counts["reel"]
        self.assertEqual("640x360", reel["resolution"])
        self.assertEqual("source", reel["resolution_measured_from"])
        edl = json.loads(Path(self.story.outputs[0]).read_text(encoding="utf-8"))
        self.assertEqual(
            {"width": 640, "height": 360}, edl["target"]["resolution"]
        )

    def test_reframe_is_on_but_declares_no_crop_where_none_is_needed(self):
        """Reframing is available now; it is still not applied for free.

        Every source in this group shares one measured geometry, so the target
        aspect matches each clip's and there is nothing to crop. The EDL must
        still SAY the reframe was checked -- `render-video` requires a passing
        finding for both reframe checks, and an absent finding would read as a
        check nobody ran.
        """
        self.assertEqual("enabled", self.story.counts["reel"]["reframe"])
        edl = json.loads(Path(self.story.outputs[0]).read_text(encoding="utf-8"))
        self.assertEqual([], edl["reframe_tracks"])
        by_id = {c["check_id"]: c for c in edl["validation"]["checks"]}
        self.assertTrue(by_id["reframe_aspect_matches_target"]["passed"])
        self.assertTrue(by_id["reframe_keyframes_ordered"]["passed"])

    def test_the_edl_validates_against_the_contract(self):
        from jsonschema import Draft202012Validator  # noqa: PLC0415
        from referencing import Registry, Resource  # noqa: PLC0415

        repo_root = Path(__file__).resolve().parents[3]
        schema_dir = repo_root / "contracts" / "schemas"
        documents = {
            path.name: json.loads(path.read_text(encoding="utf-8"))
            for path in sorted(schema_dir.glob("*.schema.json"))
        }
        registry = Registry().with_resources(
            [(name, Resource.from_contents(doc)) for name, doc in documents.items()]
        )
        validator = Draft202012Validator(
            documents["edl.schema.json"], registry=registry
        )
        edl = json.loads(Path(self.story.outputs[0]).read_text(encoding="utf-8"))
        errors = sorted(validator.iter_errors(edl), key=lambda e: list(e.path))
        self.assertEqual(
            [], errors, "; ".join(f"{list(e.path)}: {e.message}" for e in errors[:3])
        )

    def test_a_second_run_re_does_nothing_and_plans_the_same_reel(self):
        again = run_pipeline(
            [self.root],
            self.workdir,
            stages=["ingest", "story"],
            settings=Settings(render_print=False, render_video=False, reel_seconds=6.0),
        )
        story = _stage(again, "story")
        self.assertEqual(StageStatus.COMPLETED, story.status, story.detail)
        self.assertEqual(0, story.counts["proxies"]["done"], "a proxy was remade")
        self.assertEqual(3, story.counts["proxies"]["already"])
        self.assertEqual(0, story.counts["moments"]["scored"], "a clip was rescored")
        self.assertEqual(3, story.counts["moments"]["already"])
        self.assertEqual(
            self.story.counts["reel"]["edl_id"],
            story.counts["reel"]["edl_id"],
            "an unchanged library planned a different reel, so edl_id is not a "
            "usable render cache key",
        )


class RenderTheReel(unittest.TestCase):
    """The deliverable: a file on disk, and the refusal path that guards it."""

    @classmethod
    def setUpClass(cls):
        require_ingest_binary()
        require_ffmpeg()
        if shutil.which("node") is None:
            raise unittest.SkipTest("node is not on PATH; render-video cannot run")
        if shutil.which("ffprobe") is None:
            raise unittest.SkipTest("ffprobe is not on PATH")
        entry = (
            Path(__file__).resolve().parents[3]
            / "workers/render-video/dist/workers/render-video/src/cli.js"
        )
        if not entry.is_file():
            raise unittest.SkipTest(
                "the video renderer is not built; "
                "cd workers/render-video && npm install && npm run build"
            )
        cls.root = Path(tempfile.mkdtemp(prefix="mep-render-src-"))
        cls.workdir = Path(tempfile.mkdtemp(prefix="mep-render-work-"))
        write_clip(cls.root / "VID_0001.mp4", seconds=2.0, rate=30, size=(320, 180))
        write_clip(
            cls.root / "VID_0002.mp4", seconds=2.0, rate=30, size=(320, 180),
            tone_hz=660,
        )
        cls.report = run_pipeline(
            [cls.root],
            cls.workdir,
            stages=["ingest", "story", "render-video"],
            settings=Settings(render_print=False, reel_seconds=4.0),
        )

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.root, ignore_errors=True)
        shutil.rmtree(cls.workdir, ignore_errors=True)

    def test_a_file_exists_and_holds_the_frames_the_plan_asked_for(self):
        result = _stage(self.report, "render-video")
        self.assertEqual(StageStatus.COMPLETED, result.status, result.detail)
        output = Path(result.outputs[0])
        self.assertTrue(output.is_file())
        self.assertGreater(output.stat().st_size, 1024)

        edl = json.loads(
            Path(_stage(self.report, "story").outputs[0]).read_text(encoding="utf-8")
        )
        timeline = sum(
            item["duration"]["value"] if item["item_type"] == "gap"
            else item["timeline_range"]["duration"]["value"]
            for track in edl["tracks"]
            if track["kind"] == "video"
            for item in track["items"]
            if item["item_type"] in ("clip", "gap")
        )
        # `counts` is keyed by EDL kind now that the stage renders every plan
        # the story stage produced rather than only the first.
        self.assertEqual(int(timeline), result.counts["reel"]["frames"])

    def test_a_second_run_does_not_re_encode(self):
        output = Path(_stage(self.report, "render-video").outputs[0])
        before = output.stat()
        again = run_pipeline(
            [self.root],
            self.workdir,
            stages=["ingest", "story", "render-video"],
            settings=Settings(render_print=False, reel_seconds=4.0),
        )
        result = _stage(again, "render-video")
        self.assertEqual(StageStatus.COMPLETED, result.status, result.detail)
        self.assertIn("verified", result.detail)
        after = output.stat()
        self.assertEqual(before.st_ino, after.st_ino, "verified reuse replaced the file")
        self.assertEqual(before.st_mtime_ns, after.st_mtime_ns, "verified reuse re-encoded")

    def test_z_a_completed_job_with_same_size_corruption_fails_verification(self):
        output = Path(_stage(self.report, "render-video").outputs[0])
        damaged = bytearray(output.read_bytes())
        damaged[-1] ^= 0xFF
        output.write_bytes(damaged)
        size = output.stat().st_size

        again = run_pipeline(
            [self.root],
            self.workdir,
            stages=["ingest", "story", "render-video"],
            settings=Settings(render_print=False, reel_seconds=4.0),
        )
        result = _stage(again, "render-video")

        self.assertEqual(size, output.stat().st_size, "the mutation did not preserve size")
        self.assertEqual(StageStatus.FAILED, result.status, result.detail)
        self.assertIn("BLAKE3", result.detail)

    def test_a_contract_gap_is_reported_with_its_issue_and_not_worked_around(self):
        """The refusal path, exercised on a real refusal.

        `audio_plan.ambient.high_pass_hz` pins a corner frequency and nothing
        about the filter's order or response, so the renderer refuses it on
        contracts#53. This test edits a planned EDL to declare one and checks
        that the stage FAILS carrying the issue number, rather than dropping the
        field, catching the error, or reporting a render that did not happen.
        """
        workdir = Path(tempfile.mkdtemp(prefix="mep-render-gap-"))
        try:
            report = run_pipeline(
                [self.root],
                workdir,
                stages=["ingest", "story"],
                settings=Settings(render_print=False, render_video=False,
                                  reel_seconds=4.0),
            )
            edl_path = Path(_stage(report, "story").outputs[0])
            edl = json.loads(edl_path.read_text(encoding="utf-8"))
            edl["audio_plan"]["ambient"]["high_pass_hz"] = 120.0
            edl_path.write_text(json.dumps(edl, indent=2), encoding="utf-8")

            # `story` re-runs, finds its plan already on disk and leaves the
            # edited file alone, so render-video reads exactly what was written.
            second = run_pipeline(
                [self.root],
                workdir,
                stages=["ingest", "story", "render-video"],
                settings=Settings(render_print=False, reel_seconds=4.0),
            )
            result = _stage(second, "render-video")
            self.assertEqual(StageStatus.FAILED, result.status, result.detail)
            self.assertIn("contracts#53", result.detail)
            self.assertIn("high_pass_hz", result.detail)
            self.assertFalse(
                list((workdir / "outputs" / "video").glob("*.mp4")),
                "a refused plan still produced a file",
            )
        finally:
            shutil.rmtree(workdir, ignore_errors=True)


class UnmeasuredGeometry(unittest.TestCase):
    """A library ingested before #78 must still plan, and must say so.

    `MediaRecord.video` is null for every record any earlier build of
    `workers/ingest` wrote. The stage has to fall back to the proxy raster and
    turn reframing off for those, exactly as it did before -- because a crop
    computed from a geometry nobody measured frames the wrong part of the shot,
    and that is invisible in the output. This drops `video` back out of a
    measured library to exercise that path against real proxies rather than
    against a mock of one.
    """

    def test_a_record_without_video_falls_back_to_the_proxy_raster(self):
        require_ingest_binary()
        require_ffmpeg()
        from memory_engine_media_db import Database  # noqa: PLC0415

        root = Path(tempfile.mkdtemp(prefix="mep-story-unmeasured-"))
        workdir = Path(tempfile.mkdtemp(prefix="mep-story-unmeasured-work-"))
        try:
            write_clip(root / "VID_0001.mp4", seconds=2.0, rate=30)
            write_clip(root / "VID_0002.mp4", seconds=2.0, rate=30, tone_hz=660)
            first = run_pipeline(
                [root],
                workdir,
                stages=["ingest", "story"],
                settings=Settings(render_print=False, render_video=False,
                                  reel_seconds=4.0),
            )
            self.assertEqual(
                "source", _stage(first, "story").counts["reel"]["resolution_measured_from"]
            )

            database = Database.open(workdir / "library.db")
            try:
                for media_id, in database.connection.execute(
                    "SELECT media_id FROM media WHERE kind = 'video'"
                ).fetchall():
                    record = database.get_media(media_id)
                    record["video"] = None
                    database.put_media(record)
            finally:
                database.close()
            shutil.rmtree(workdir / "outputs" / "edl", ignore_errors=True)

            again = _stage(
                run_pipeline(
                    [root],
                    workdir,
                    stages=["ingest", "story"],
                    settings=Settings(render_print=False, render_video=False,
                                      reel_seconds=4.0),
                ),
                "story",
            )
            self.assertEqual(StageStatus.COMPLETED, again.status, again.detail)
            reel = again.counts["reel"]
            # The proxy raster, which is 854x480 for a 640x360 source.
            self.assertEqual("854x480", reel["resolution"])
            self.assertEqual("proxy", reel["resolution_measured_from"])
            self.assertIn("disabled", reel["reframe"])
            self.assertIn("proxy raster", again.detail)
            edl = json.loads(Path(again.outputs[0]).read_text(encoding="utf-8"))
            self.assertEqual([], edl["reframe_tracks"])
        finally:
            shutil.rmtree(root, ignore_errors=True)
            shutil.rmtree(workdir, ignore_errors=True)


class FilmFromTheLibrary(unittest.TestCase):
    """The third output, end to end: moments -> `plan_film` -> a playable file.

    The library here is deliberately longer than `StoryStage`'s. Two seconds of
    footage is one moment, and a film planned from two moments is the thing
    this pipeline refuses to make; six seconds a clip gives the moment scorer
    room to find several, which is what a three-act arc needs.
    """

    @classmethod
    def setUpClass(cls):
        require_ingest_binary()
        require_ffmpeg()
        if shutil.which("node") is None:
            raise unittest.SkipTest("node is not on PATH; render-video cannot run")
        if shutil.which("ffprobe") is None:
            raise unittest.SkipTest("ffprobe is not on PATH")
        entry = (
            Path(__file__).resolve().parents[3]
            / "workers/render-video/dist/workers/render-video/src/cli.js"
        )
        if not entry.is_file():
            raise unittest.SkipTest("the video renderer is not built")
        cls.root = Path(tempfile.mkdtemp(prefix="mep-film-src-"))
        cls.workdir = Path(tempfile.mkdtemp(prefix="mep-film-work-"))
        for index, tone in enumerate((440, 660, 220), start=1):
            write_clip(
                cls.root / f"VID_{index:04d}.mp4",
                seconds=6.0,
                rate=30,
                size=(320, 180),
                tone_hz=tone,
            )
        cls.report = run_pipeline(
            [cls.root],
            cls.workdir,
            stages=["ingest", "story", "render-video"],
            settings=Settings(render_print=False, reel_seconds=6.0),
        )
        cls.story = _stage(cls.report, "story")
        cls.render = _stage(cls.report, "render-video")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.root, ignore_errors=True)
        shutil.rmtree(cls.workdir, ignore_errors=True)

    def _film_edl(self) -> dict:
        for path in self.story.outputs:
            edl = json.loads(Path(path).read_text(encoding="utf-8"))
            if edl["kind"] == "film":
                return edl
        raise AssertionError(f"no film EDL among {self.story.outputs}")

    def test_the_stage_produced_a_reel_and_a_film_from_the_same_pool(self):
        self.assertEqual(StageStatus.COMPLETED, self.story.status, self.story.detail)
        kinds = [
            json.loads(Path(path).read_text(encoding="utf-8"))["kind"]
            for path in self.story.outputs
        ]
        self.assertEqual(["reel", "film"], kinds)
        reel = self.story.counts["reel"]
        film = self.story.counts["film"]
        self.assertNotEqual(reel["edl_id"], film["edl_id"])
        # Same footage, deliberately: two answers to two questions would make
        # "why is this shot in one and not the other" unanswerable.
        self.assertEqual(reel["sources"], film["sources"])
        self.assertEqual(reel["moments_available"], film["moments_available"])

    def test_the_film_is_longer_than_the_reel_and_holds_its_shots(self):
        reel = self.story.counts["reel"]
        film = self.story.counts["film"]
        self.assertGreater(film["duration_s"], reel["duration_s"])
        self.assertGreaterEqual(film["clips"], 3)
        self.assertTrue(all(seconds > 0 for seconds in film["shot_seconds"]))

    def test_the_film_carries_a_three_act_arc_with_every_required_beat_met(self):
        edl = self._film_edl()
        arc = edl["story_arc"]
        self.assertEqual("three_act", arc["template"])
        self.assertEqual(
            ["act-setup", "act-development", "act-resolution"],
            [act["act_id"] for act in arc["acts"]],
        )
        for act in arc["acts"]:
            for beat in act["beats"]:
                if beat["required"]:
                    self.assertTrue(
                        beat["satisfied_by_clip_ids"], beat["beat_id"]
                    )
        by_id = {c["check_id"]: c for c in edl["validation"]["checks"]}
        self.assertTrue(by_id["required_story_beats_satisfied"]["passed"])
        self.assertEqual("pass", edl["validation"]["status"])

    def test_the_film_claims_no_word_safe_cut_it_cannot_prove(self):
        """The film loses more to the missing transcript than the reel does,
        and the run has to say so rather than let the absence read as a pass."""
        edl = self._film_edl()
        ids = {check["check_id"] for check in edl["validation"]["checks"]}
        self.assertNotIn("no_mid_word_cut", ids)
        self.assertEqual(0, self.story.counts["film"]["word_safe_cuts_certified"])
        self.assertEqual(0, self.story.counts["film"]["l_cuts"])
        self.assertIn("word-safe", self.story.detail)

    def test_the_film_declares_its_chronology_rather_than_implying_one(self):
        """Every clip here has `precision: unknown`, so the film is given no
        capture order and says so instead of ordering by content hash and
        calling the result a story."""
        self.assertEqual(
            "declaration_order", self.story.counts["film"]["chronology"]
        )

    def test_the_film_validates_against_the_contract(self):
        from jsonschema import Draft202012Validator  # noqa: PLC0415
        from referencing import Registry, Resource  # noqa: PLC0415

        schema_dir = Path(__file__).resolve().parents[3] / "contracts" / "schemas"
        documents = {
            path.name: json.loads(path.read_text(encoding="utf-8"))
            for path in sorted(schema_dir.glob("*.schema.json"))
        }
        registry = Registry().with_resources(
            [(name, Resource.from_contents(doc)) for name, doc in documents.items()]
        )
        validator = Draft202012Validator(documents["edl.schema.json"], registry=registry)
        errors = sorted(
            validator.iter_errors(self._film_edl()), key=lambda e: list(e.path)
        )
        self.assertEqual(
            [], errors, "; ".join(f"{list(e.path)}: {e.message}" for e in errors[:3])
        )

    def test_the_renderer_produced_a_film_file_of_the_length_the_plan_states(self):
        """A plan no renderer accepts is not a plan. This is the assertion that
        makes the film a deliverable rather than a document."""
        self.assertEqual(StageStatus.COMPLETED, self.render.status, self.render.detail)
        self.assertEqual(2, len(self.render.outputs))
        film = self._film_edl()
        counts = self.render.counts["film"]
        self.assertEqual(film["edl_id"], counts["edl_id"])
        timeline = sum(
            item["duration"]["value"] if item["item_type"] == "gap"
            else item["timeline_range"]["duration"]["value"]
            for track in film["tracks"]
            if track["kind"] == "video"
            for item in track["items"]
            if item["item_type"] in ("clip", "gap")
        )
        self.assertEqual(int(timeline), counts["frames"])
        output = self.workdir / "outputs" / "video" / f"{film['edl_id']}.mp4"
        self.assertTrue(output.is_file())
        self.assertGreater(output.stat().st_size, 1024)


class NoVideo(unittest.TestCase):
    def test_a_library_with_no_video_is_skipped_rather_than_failed(self):
        require_ingest_binary()
        from support import make_library  # noqa: PLC0415

        root = Path(tempfile.mkdtemp(prefix="mep-story-photos-"))
        workdir = Path(tempfile.mkdtemp(prefix="mep-story-photos-work-"))
        try:
            make_library(root, 2, size=(640, 480))
            report = run_pipeline(
                [root],
                workdir,
                stages=["ingest", "story"],
                settings=Settings(render_print=False, render_video=False),
            )
            story = _stage(report, "story")
            self.assertEqual(StageStatus.SKIPPED, story.status, story.detail)
            self.assertEqual(0, story.counts["videos"])
        finally:
            shutil.rmtree(root, ignore_errors=True)
            shutil.rmtree(workdir, ignore_errors=True)


class NoProxyGenerator(unittest.TestCase):
    def test_an_unbuilt_ingest_worker_is_unavailable_not_empty(self):
        """A library full of video and no way to decode it is not "no moments".

        UNAVAILABLE and SKIPPED are different answers and only one of them means
        the library is finished. Pointing the runner at a repo root with no
        built worker in it is the same condition a fresh checkout is in.
        """
        require_ingest_binary()
        require_ffmpeg()
        root = Path(tempfile.mkdtemp(prefix="mep-story-nobin-"))
        workdir = Path(tempfile.mkdtemp(prefix="mep-story-nobin-work-"))
        empty_root = Path(tempfile.mkdtemp(prefix="mep-story-nobin-repo-"))
        try:
            write_clip(root / "VID_0001.mp4", seconds=1.0, rate=30)
            report = run_pipeline(
                [root],
                workdir,
                stages=["ingest", "story"],
                settings=Settings(render_print=False, render_video=False),
            )
            self.assertEqual(StageStatus.COMPLETED, _stage(report, "ingest").status)

            blind = run_pipeline(
                [root],
                workdir,
                stages=["story"],
                settings=Settings(render_print=False, render_video=False),
                repo_root=empty_root,
            )
            story = _stage(blind, "story")
            self.assertEqual(StageStatus.UNAVAILABLE, story.status, story.detail)
            self.assertIn("cargo build", story.detail)
        finally:
            for path in (root, workdir, empty_root):
                shutil.rmtree(path, ignore_errors=True)


if __name__ == "__main__":
    unittest.main()
